### ISSUE TITLE
Проблемы с CORS headers

### ISSUE THREAD

**Issue by f1xgun** [mospolytech-finapp/backend-archive#1]
Необходимо установить библиотеку [django-cors-headers](https://pypi.org/project/django-cors-headers/)

```
CORS_ALLOWED_ORIGINS = [
    "https://web-mospolytech-finapp.vercel.app/",
    "http://127.0.0.1:5173",
]
```
![image](https://user-images.githubusercontent.com/88651829/234689249-f4df980a-0935-481b-93cb-0c49e62fb378.png)

**Comment by Nejern** [comment]
Зачем?

**Comment by yakser** [comment]
> Зачем?

Фронт не может делать запросы на бэкенд сервер без указанных CORS header'ов. На скрине видно что запрос блокируется браузером...
Почитай [MDN](https://developer.mozilla.org/ru/docs/Web/HTTP/CORS)
