### ISSUE TITLE
Недочеты в модели Transaction

### ISSUE THREAD

**Issue by f1xgun** [mospolytech-finapp/backend-archive#2]
Почему time необязательный? Лучше объединить поля time, date в одно поле DateTimeField, которое будет обязательным. 

user_id надо заменить на user, поскольку user_id будет инстансом user в django orm
id по дефолту read_only field, так как оно PK, unique, AI, так что можно удалить его из read_only_fields в serializers
метод create по дефолту имеется, можно удалить
уверены ли вы, что не будет ошибок с дробными числами в погрешностях при делении и сложении? 0.1 + 0.2 == 0.3?

**Comment by Nejern** [comment]
> Почему time необязательный? Лучше объединить поля time, date в одно поле DateTimeField, которое будет обязательным.

См. файл концепции «Релиз 02»

> user_id надо заменить на user, поскольку user_id будет инстансом user в django orm

Заменим на "owner"

> id по дефолту read_only field, так как оно PK, unique, AI, так что можно удалить его из read_only_fields в serializers

Удалим

> метод create по дефолту имеется, можно удалить

Нельзя. В нашем методе отдельно прописан авторизованный юзер

> уверены ли вы, что не будет ошибок с дробными числами в погрешностях при делении и сложении? 0.1 + 0.2 == 0.3?

Уверен.
См. https://docs.python.org/3/library/decimal.html#module-decimal
