### ISSUE TITLE
Кривая система оповещения о неверном пароле при регистрации

### ISSUE THREAD

**Issue by tlyashok** [mospolytech-finapp/backend-archive#6]
## 🚨Описание проблемы

Требования к паролю нигде не указаны, при этом пароль должен соблюдать четыре условия (цифра, заглавная буква, специальный символ, длина пароля), но даже если не соблюдены все четыре условия, выводится сообщение только об одном из условий.

## 🔍Воспроизведение проблемы

Для воспроизведения проблемы вводимый при регистрации пароль должен не соотвествовать требованиям безопасности.

## 👀Ожидаемое поведение

Должно быть пояснение, какие символы должны присутствовать в пароле, какой длины должен быть пароль.

## 💥Фактическое поведение

Выводится уведомление только об одном несоблюдённом условии.

## 💻Компьютерная версий
ОС: Windows 11
Браузер: Chrome
Версия: 113.0.5672.93

## 📷Скриншоты/видео

![image](https://github.com/mospolytech-finapp/web/assets/67411791/adcd8628-cd33-4945-bd57-59836a8eb1e3)

***🔥Критичность***
Средняя

**Comment by Sh1mpi** [comment]
это к беку

**Comment by Nejern** [comment]
это к вебу
